Add Dolphin and Konsole to the list
mpsq/arewewaylandyet pull request #35
Opened 2020-11-05 19:26 UTC by smirkybg

Signed-off-by: Bogomil Vasilev <smirky@smirky.net>

2020-11-05 20:33 UTC, mpsq requested changes
Minor change: sorting the list alphabetically. It looks good otherwise, thanks for your contribution :muscle:.

2020-11-05 20:33 UTC, mpsq commented on src/index.html
> +            <a href="https://github.com/KDE/konsole">Konsole</a>
```suggestion
            <a href="https://sw.kovidgoyal.net/kitty/">Kitty</a>,
            <a href="https://github.com/KDE/konsole">Konsole</a>,
            <a href="https://launchpad.net/sakura">Sakura</a>,
            <a href="https://github.com/thestinger/termite">Termite</a>
```

2020-11-05 20:33 UTC, mpsq approved these changes

2020-11-05 20:33 UTC, merged

2020-11-07 16:24 UTC, smirkybg commented
You seem to ditched my contribution to your list little after merging it. Something related to the webserver change I suppose?

2020-11-08 20:06 UTC, mpsq commented
Thanks, I just fixed it :)